- name: update_repos
  hosts: "{{ nodes }}"
  tasks:
    - name: Find git path
      find:
        paths: "{{ HOME }}"
        patterns: "git"
        recurse: true
        file_type: "directory"
        depth: 3
      register: git_paths
    - set_fact:
        git_path: "{{ git_paths.files[0] }}"
      when: "{{ git_paths.files | length }} > 0"
    - name: Fetch repos
      find:
        paths: "{{ git_path.path }}"
        file_type: "directory"
        depth: 1
      register: repos
    - name: Ensure paramiko
      shell: "pip3 install paramiko"
    - name: Pull repos
      loop: "{{ repos.files }}"
      command: python3
      args:
        stdin: |
          import paramiko
          s = paramiko.SSHClient()
          s.load_system_host_keys()
          s.connect('127.0.0.1', 22, '{{ ansible_ssh_user }}', '{{ ansible_ssh_pass }}')
          s.exec_command('git -C {{ item.path }} pull')
          s.close()

